import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import AccountancyCalc from '../AccountancyCalc';
import userEvent from '@testing-library/user-event';

// Mock CalculatorRoom to simplify rendering
vi.mock('../CalculatorRoom', () => ({
  CalculatorRoom: ({ children, isOpen, title }: any) => {
    if (!isOpen) return null;
    return <div data-testid={`room-${title.toLowerCase().replace(/[^a-z0-9]/g, '-')}`}>{children}</div>;
  }
}));

// Mock ValidatedInput to simplify input tracking
vi.mock('../ValidatedInput', () => ({
  ValidatedInput: ({ label, value, onChange, placeholder }: any) => (
    <div>
      <label htmlFor={`input-${label}`}>{label}</label>
      <input
        id={`input-${label}`}
        data-testid={`input-${label}`}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
      />
    </div>
  )
}));

// We do NOT mock ResultDisplay so we test actual DOM elements generated by the calculator,
// or we mock it properly if it's imported correctly.
// Let's mock it properly by intercepting the named export from CalculatorCard
vi.mock('../CalculatorCard', () => ({
  ResultDisplay: ({ label, value, unit }: any) => (
    <div data-testid={`result-${label}`}>
      <span data-testid={`label-${label}`}>{label}</span>
      <span data-testid={`val-${label}`}>{value}</span>
      <span data-testid={`unit-${label}`}>{unit}</span>
    </div>
  ),
  CalculatorCard: ({ children }: any) => <div>{children}</div>
}));


describe('AccountancyCalc', () => {
  const defaultProps = {
    activeId: null,
    onClose: vi.fn(),
  };

  it('renders nothing when activeId is null', () => {
    render(<AccountancyCalc {...defaultProps} />);
    expect(screen.queryByTestId(/room-/)).toBeNull();
  });

  describe('Ratio Analysis', () => {
    it('calculates Current Ratio and Debt-Equity correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="ratios" />);

      const user = userEvent.setup();

      await user.type(screen.getByTestId('input-Current Assets'), '100000');
      await user.type(screen.getByTestId('input-Current Liabilities'), '50000');

      await user.type(screen.getByTestId('input-Total Debt'), '200000');
      await user.type(screen.getByTestId('input-Shareholders\' Equity'), '100000');

      expect(screen.getByTestId('val-Current Ratio')).toHaveTextContent('2.00');
      expect(screen.getByTestId('val-Debt-Equity')).toHaveTextContent('2.00');
    });

    it('handles division by zero in Ratio Analysis gracefully', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="ratios" />);
      const user = userEvent.setup();

      // Empty values should result in 0.00
      expect(screen.getByTestId('val-Current Ratio')).toHaveTextContent('0.00');

      await user.type(screen.getByTestId('input-Current Assets'), '100000');
      await user.type(screen.getByTestId('input-Current Liabilities'), '0');

      // Wait for it to become Infinity or NaN, checking what UI renders
      expect(screen.getByTestId('val-Current Ratio').textContent).not.toBe('');
    });
  });

  describe('Partnership Basics', () => {
    it('calculates Interest on Drawings correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="partnership" />);
      const user = userEvent.setup();

      await user.type(screen.getByTestId('input-Total Drawings'), '12000');
      await user.type(screen.getByTestId('input-Interest Rate (%)'), '10');

      expect(screen.getByTestId('val-Interest on Drawings')).toHaveTextContent('650.00');

      await user.selectOptions(screen.getByRole('combobox'), '6');
      expect(screen.getByTestId('val-Interest on Drawings')).toHaveTextContent('600.00');

      await user.selectOptions(screen.getByRole('combobox'), '5.5');
      expect(screen.getByTestId('val-Interest on Drawings')).toHaveTextContent('550.00');
    });
  });

  describe('NPSR & Sacrificing Ratio', () => {
    it('calculates NPSR correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="npsr" />);
      const user = userEvent.setup();

      await user.clear(screen.getByTestId('input-Old Ratio (Partner A)'));
      await user.clear(screen.getByTestId('input-Old Ratio (Partner B)'));
      await user.clear(screen.getByTestId("input-New Partner's Share (Denominator)"));

      await user.type(screen.getByTestId('input-Old Ratio (Partner A)'), '3');
      await user.type(screen.getByTestId('input-Old Ratio (Partner B)'), '2');
      await user.type(screen.getByTestId("input-New Partner's Share (Denominator)"), '5');

      expect(screen.getByText('2.4 : 1.6 : 1')).toBeInTheDocument();
    });
  });

  describe('Issue of Shares (Pro-rata)', () => {
    it('calculates Excess Application Money correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="shares" />);
      const user = userEvent.setup();

      await user.type(screen.getByTestId('input-Shares Applied'), '150000');
      await user.type(screen.getByTestId('input-Shares Allotted'), '100000');
      await user.type(screen.getByTestId('input-Application Money per Share'), '3');

      expect(screen.getByTestId('val-Excess Application Money')).toHaveTextContent('150000.00');
    });
  });

  describe('Goodwill Valuation', () => {
    it('calculates Goodwill (Super Profit Method) correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="goodwill" />);
      const user = userEvent.setup();

      await user.type(screen.getByTestId('input-Average Profit'), '50000');
      await user.type(screen.getByTestId('input-Normal Rate of Return (%)'), '10');
      await user.type(screen.getByTestId('input-Capital Employed'), '300000');

      await user.clear(screen.getByTestId('input-No. of Years Purchase'));
      await user.type(screen.getByTestId('input-No. of Years Purchase'), '3');

      expect(screen.getByTestId('val-Goodwill (Super Profit Method)')).toHaveTextContent('60000.00');
    });
  });

  describe('Depreciation', () => {
    it('calculates WDV after N Years correctly', async () => {
      render(<AccountancyCalc {...defaultProps} activeId="depreciation" />);
      const user = userEvent.setup();

      await user.type(screen.getByTestId('input-Original Cost'), '100000');
      await user.type(screen.getByTestId('input-Depreciation Rate (%)'), '10');

      await user.clear(screen.getByTestId('input-Number of Years'));
      await user.type(screen.getByTestId('input-Number of Years'), '2');

      expect(screen.getByTestId('val-WDV after N Years')).toHaveTextContent('81000.00');
    });
  });
});
